# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
        logLevel:
          description: 'Log level'     
          required: false
          default: 'warning' 
          type: choice
          options:
          - info
          - warning
          - debug 
        tags:
          description: 'Test scenario tags'
          required: false 
          type: boolean
          
jobs:
  deployDev:
    name: Deploy to Development
    if: github.ref_type == 'tag' 
    runs-on: ubuntu-latest
    environment:
      name: Drive-development
      url: https://drive.google.com/drive/folders/1opYibO_CQTVMNVLa6r8eQgr83LUl7OhG?usp=sharing

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    
    - name: Build package
      run: python -m build

    - name: Archive files
      run: |
          sudo apt-get update
          sudo apt-get install zip
          zip -r archive.zip *
