# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Release
on:
  release:
    types: [released]  
  workflow_dispatch:
    inputs:
        Tag:
          description: 'Enter the tag name to use'     
          required: true 
          type: string
        Release_Name:
          description: 'Enter the release name'
          required: true 
          type: string
        Release_Note:
          description: 'Enter the release note data'
          required: false 
          type: string
        Pre_Release:
          description: 'check if it is a pre-release'
          type: boolean
          default: false
          required: false
                
jobs:
  Test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        
    - name: Test with pytest
      run: |
        pytest -v --cov=CodeCoverageReport 
  
  CreateRelease:
   runs-on: ubuntu-latest
   needs: Test
   steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          tag_name: ${{ inputs.Tag }}
          release_name: Release ${{ inputs.Release_Name }}
          draft: false
          prerelease: false
          
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: artifact
        path: |
          ${{ github.workspace }}/BasicOperation.py
          ${{ github.workspace }}/requirements.txt
          ${{ github.workspace }}/LICENSE
          ${{ github.workspace }}/README.md
        if-no-files-found: error
        retention-days: 10
      
