# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Release
on:
  release:
    types: [released]  
  workflow_dispatch:
    inputs:
        Tag:
          description: 'Enter the tag name to use'     
          required: true 
          type: string
        Release_Name:
          description: 'Enter the release name'
          required: true 
          type: string
        Release_Note:
          description: 'Enter the release note data'
          required: false 
          type: string
        Pre_Release:
          description: 'To Do Pre-Release'
          type: boolean
          default: false
          required: false
          
jobs:
  Test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        
    - name: Test with pytest
      run: |
        pytest -v --cov=CodeCoverageReport 
  
  CreateRelease:
   runs-on: ubuntu-latest
   needs: Test
   steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Upload a Build Artifact
      id: Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: artifact
        path: |
          ${{ github.workspace }}/BasicOperation.py
          ${{ github.workspace }}/requirements.txt
          ${{ github.workspace }}/LICENSE
          ${{ github.workspace }}/README.md
        if-no-files-found: error
        retention-days: 10
      
    - name: Release
      uses: softprops/action-gh-release@v0.1.14
      with: 
        # Note-worthy description of changes in release
        body: ${{ inputs.Release_Note }}
        # Gives the release a custom name. Defaults to tag name
        name: ${{ inputs.Release_Name }}
        # Gives a tag name. Defaults to github.GITHUB_REF
        tag_name: ${{ inputs.Tag }}
        # Identify the release as a prerelease. Defaults to false
        prerelease: ${{ inputs.Pre_Release }}
        # Whether to automatically generate the name and body for this release. If name is specified, the specified name will be used; otherwise, a name will be automatically generated. If body is specified, the body will be pre-pended to the automatically generated notes.
        generate_release_notes: true
        files: artifact.zip
